# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciclo', models.PositiveSmallIntegerField()),
                ('en_campo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('fecha_instalacion', models.DateTimeField()),
                ('on', models.BooleanField()),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Tipo_ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='tipo_sensor',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Variable'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Tipo_sensor'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='tipo_nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Tipo_nodo'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Ubicacion'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Sensor'),
        ),
    ]
